"                                                                            \n"
"Copyright (c) 2004/2005 Thomas Fuchs / The Rockin'-B, www.rockin-b.de       \n"
"                                                                            \n"
"Permission is granted to anyone to use this software for any purpose        \n"
"and to redistribute it freely, subject to the following restrictions:       \n"
"                                                                            \n"
"1.  The origin of this software must not be misrepresented. You must not    \n"
"    claim that you wrote the original software. If you use this software    \n"
"    in a product, an acknowledgment in the product documentation would be   \n"
"    appreciated but is not required.                                        \n"
"                                                                            \n"
"2.  ANY COMMERCIAL USE IS PROHIBITED. This includes that you must not use   \n"
"    this software in the production of a commercial product. Only an explicit\n"
"    permission by the author can allow you to do that.                      \n"
"                                                                            \n"
"3.  Any modification applied to the software must be marked as such clearly.\n"
"                                                                            \n"
"4.  This license may not be removed or altered from any distribution.       \n"
"                                                                            \n"
"                                                                            \n"
"			    NO WARRANTY                                                  \n"
"                                                                            \n"
"THERE IS NO WARRANTY FOR THE PROGRAM.                                       \n"
"THE PROGRAM IS PROVIDED \"AS IS\" WITHOUT WARRANTY OF ANY KIND,             \n"
"EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,                 \n"
"THE IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE.                 \n"
"THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU.\n"
"SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY    \n"
"SERVICING, REPAIR OR CORRECTION.                                            \n"
"                                                                            \n"
"IN NO EVENT WILL THE COPYRIGHT HOLDER BE LIABLE TO YOU FOR DAMAGES,         \n"
"INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING \n"
"OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED   \n"
"TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY    \n"
"YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER  \n"
"PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE       \n"
"POSSIBILITY OF SUCH DAMAGES.                                                \n"
"                                                                            \n"
